2020-09-24 09:46:32,578 ERROR 9900 [-/127.0.0.1/-/34ms POST /editinfo] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: 'Wed Sep 16 2020 00:00:00 GMT+0800 (中国标准时间)' for column 'birth' at row 1
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\21cake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\21cake\cake\server\node_modules\co\index.js:54:5
    sql: update user set name="ads",email="1255274497@qq.com",birth="Wed Sep 16 2020 00:00:00 GMT+0800 (中国标准时间)" ,sex="女"
        where phone="18212418574"
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect date value: 'Wed Sep 16 2020 00:00:00 GMT+0800 (中国标准时间)' for column 'birth' at row 1"
sqlState: "22007"
index: 0
sql: "update user set name=\"ads\",email=\"1255274497@qq.com\",birth=\"Wed Sep 16 2020 00:00:00 GMT+0800 (中国标准时间)\" ,sex=\"女\"\n        where phone=\"18212418574\""
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 9900
hostname: DESKTOP-K5ULKD4

2020-09-24 09:53:03,539 ERROR 2588 [-/127.0.0.1/-/12ms POST /editinfo] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: 'Thu Sep 17 2020 00:00:00 GMT+0800 (中国标准时间)' for column 'birth' at row 1
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\21cake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\21cake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\21cake\cake\server\node_modules\co\index.js:54:5
    sql: update user set name="zfvc",email="1255274497@qq.com",birth="Thu Sep 17 2020 00:00:00 GMT+0800 (中国标准时间)" ,sex="男"
        where phone="18212418574"
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect date value: 'Thu Sep 17 2020 00:00:00 GMT+0800 (中国标准时间)' for column 'birth' at row 1"
sqlState: "22007"
index: 0
sql: "update user set name=\"zfvc\",email=\"1255274497@qq.com\",birth=\"Thu Sep 17 2020 00:00:00 GMT+0800 (中国标准时间)\" ,sex=\"男\"\n        where phone=\"18212418574\""
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 2588
hostname: DESKTOP-K5ULKD4

2020-09-24 12:52:14,557 ERROR 16316 nodejs.ClusterClientNoResponseError: client no response in 937634ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\12552\Desktop\21cake\cake\server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 16316
hostname: DESKTOP-K5ULKD4

